project:
  type: book

book:
  title: "fish-habitat-mapping"
  author: "Norah Jones"
  date: "5/23/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - existing_fish_obs.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

