project:
  type: book
  output-dir: docs

book:
  title: "fish-habitat-mapping"
  repo-url: https://github.com/Kenai-Watershed-Forum/fish-habitat-mapping
  author: "Benjamin Meyer"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - focus_areas.qmd
    - existing_fish_obs.qmd
    - fish_status.qmd
    - field_site_selection.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
#  pdf:
#    documentclass: scrreprt

editor: visual

